version: '3.9'

services:

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    depends_on:
      - ml-service

  ml-service:
    build: ./ml-service
    ports:
      - "5001:5001"